version: "3.9"

services:
  nodered:
    build: .
    container_name: nodered-r700
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      - TZ=America/Sao_Paulo
      - EXTERNAL_API_KEY=${EXTERNAL_API_KEY}
    volumes:
      - ./data:/data
