version: "3.7"
services:
  node-red:
    container_name: nodered-r700
    image: nodered/node-red:latest
    environment:
      - TZ=America/Sao_Paulo
      - EXTERNAL_API_KEY=${EXTERNAL_API_KEY}
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
